### ISSUE TITLE
Error parsing dependencies when encountering double quotes.

### ISSUE THREAD

**Issue by ShenTom** [tonyo/django-migration-checker#8]
* django-migration-checker version: 0.6.0
* Python version: 3.9.0
* Operating System: OSX Big Sur.

### Description

The conflict checker gave a false positive result when the dependencies in the migration files are defined with double quotes.

### What I Did
Ran the conflict checker with a migration file using double quotes to define dependencies.

### Suggestions

1. Update the regex to accept double-quotes as well.
2. Improve the error message when detecting a double quote.

**Comment by Fullchee** [comment]
We might just need to update the regex

https://github.com/tonyo/django-migration-checker/blob/master/django_migration_checker/base.py#L20
